version: '3.8'

services:
  app:
    build: ./
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_URL=$REACT_APP_API_URL
      - REACT_APP_WEBSOCKET_URL=$REACT_APP_WEBSOCKET_URL